package com.example.pruebaapp;

public enum TipoPokeES{

    NORMAL, LUCHA, VOLADOR, VENENO, TIERRA, ROCA, INSECTO, FANTASMA, ACERO, FUEGO,
    AGUA, PLANTA, ELECTRICO, PSIQUICO, HIELO, DRAGON, OSCURIDAD, HADA, DESCONOCIDO, SOMBRA

}
